server:
  port: 8085
spring:
  datasource:
    #url: jdbc:h2:file:~/h2/data/cd
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
